### ISSUE TITLE
Exception when retrieving cluster tags

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-REST#16]
[2019-09-25 08:24:02,972] ERROR in app: Exception on /btc/address/1EJ1VdgUKwGxm7i5eBeptYUM9LetGGYxX6/cluster_with_tags [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 103, in wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flask_restplus/marshalling.py", line 136, in wrapper
    resp = f(*args, **kwargs)
  File "./graphsenserest.py", line 755, in get
    address_cluster = gd.query_address_cluster(currency, address)
  File "./graphsensedao.py", line 163, in query_address_cluster
    ret = cluster_obj.__dict__
AttributeError: 'NoneType' object has no attribute '__dict__'

**Comment by defconst** [comment]
Not reproducible after regeneration of keyspace.
```
curl -X GET "http://spark-master:9000/btc/address/1EJ1VdgUKwGxm7i5eBeptYUM9LetGGYxX6/cluster_with_tags" -H "accept: application/json" -H "Authorization: Bearer ..."
{"balance": {"eur": 0.0, "satoshi": 0, "usd": 0.0}, "cluster": 327765612, "firstTx": {"height": 494523, "timestamp": 1510781901, "tx_hash": "5e6538307d559357cbee6aba23ab02a20434c47a66dcb7d552192f116aa9ef60"}, "lastTx": {"height": 494526, "timestamp": 1510782396, "tx_hash": "9d919b360ded9f265b9aa01d01507498854f85d07b7da4b4e03633fb7d172253"}, "noAddresses": 2, "inDegree": 2, "outDegree": 2, "noIncomingTxs": 2, "noOutgoingTxs": 1, "totalReceived": {"eur": 11817.87, "satoshi": 191095733, "usd": 13909.86}, "totalSpent": {"eur": 11817.87, "satoshi": 191095733, "usd": 13909.86}, "tags": []}
```
